language: java
env:
  matrix:
  - IDEA_VERSION=IC-15.0.4
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
    secure: "IkkSVd8tRYLt4h3eO8D1kUmypC1u8DiThYInTVn3EFTPEF3nSMhhcK29V47+G3oq5Uu+a3xbX0ssGqQ3l6DaZy7WLIbUXBIcUtGj4YalpQiGD7vUoHKWkUYpolqVYy2s64f1rHgUfnDep47X52ksDRwHZ8/Ouz1JoiE+TA3/DRr2V17xRRd4qaaxIh7Qyf0/17RS2ZpZznX1IikrLF+Sjluo8CxiHrhQjZo+/pBJFRmXEvmf05m0gtDCVxkvIYkm2pEFVRd7w4HsSARxq0kYgPh63NTXkkgAcvv5Y3NcSUUpFjm5ctrXVLHVGfmad14dZeUasspB77x8haO+iXQISJ17Y+HUpVstv/eZfbZ7TjrHszWYJ/y3Yycwsz5I1esvPOgr5/AfhC2BrT6B8eEgcxfb2kjCqtPZusr4gWS+RHm1InIiyKDskd76znB4Lw0/8OPwHjID9h9yGc2qDALNv5SbyuL7KX/vxkoJBk4VELLQ1jfOo7dJzuKuuZDb1ahCIDmgUXzh1i2SUnMQgoSWhhfU0RPziN6MmRAh5IBowFyBRVJWlne6fmh9UGFx3ud5iIw1KXVDgAQqsI8q5Mx8N7URXjoWWqzuHa+duDzcZuxO4u4iMBvT7yktNX2SxxLoeqxeSEhpeS3QQ0c7uIKgAmNfJdw8tt0Q05irR5gq9sA="
jdk:
- oraclejdk7
- oraclejdk8
script:
- ./gradlew test -PideaVersion=$IDEA_VERSION
notifications:
  email: false
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
after_success:
- .travis/after_success.sh
